version: '3.8'

services:
  crawler:
    image: slocksert/g1crawler:v3
    container_name: g1
    env_file:
      - .env
    ports:
    - 80:80
    networks:
      - api-python

networks:
  api-python:
    external: true